services:
  promiseassetsfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-js-promise:assets
    container_name: promise-assets-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
